[book]
authors = ["Denis Gorbachev"]
language = "en"
multilingual = true
src = "src"
title = "Coliquidity"

[output.html]
edit-url-template = "https://github.com/Coliquidity/docs/edit/main/{path}"
git-repository-url = "https://github.com/Coliquidity/docs"
git-repository-icon = "fa-github"
